info:
  new: Demo
  stuff: Hello World

---
spring:
  profiles: cloud
  platform:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://${PREFIX:}${configserver.${application.domain:cfapps.io}}}
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
cloudfoundry:
  service:
    definition:
      metadata:
        uri: http://${spring.application.name}.${application.domain:cfapps.io}
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://${PREFIX:}eureka.${application.domain:cfapps.io}}/v2/
